import {
  Amphora,
  Apple,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  AtSign,
  Award,
  BadgeCheck,
  BadgeInfo,
  Banana,
  BookOpenCheck,
  BottleWine,
  BriefcaseBusiness,
  CalendarCheck,
  CalendarDays,
  Check,
  ChefHat,
  Cherry,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsDownUp,
  ChevronsUpDown,
  ChevronUp,
  CirclePlay,
  CircleStar,
  Citrus,
  ClipboardCheck,
  Clock,
  ConciergeBell,
  Cookie,
  Copy,
  CornerRightUp,
  Croissant,
  Crown,
  Download,
  Droplets,
  ExternalLink,
  Facebook,
  FileBadge,
  FileText,
  Fish,
  Flame,
  FlaskConical,
  Flower2,
  Gem,
  GlassWater,
  Globe,
  Grape,
  Handshake,
  HouseHeart,
  Instagram,
  Layers,
  Leaf,
  Linkedin,
  List,
  LoaderCircle,
  Lock,
  LockKeyhole,
  LockKeyholeOpen,
  LockOpen,
  LogIn,
  Mail,
  MapPin,
  Martini,
  Medal,
  Menu,
  Mountain,
  Nut,
  PhoneCall,
  PhoneIncoming,
  PhoneOutgoing,
  Plus,
  Search,
  ShieldCheck,
  ShieldEllipsis,
  Snowflake,
  Sparkles,
  Sprout,
  Star,
  Sun,
  ThermometerSnowflake,
  Trash,
  Trophy,
  User,
  UserCog,
  UserRoundCheck,
  UserStar,
  Users,
  UtensilsCrossed,
  Wheat,
  Wine,
  X,
  Youtube,
} from "lucide-react";

export const iconMap = {
  amphora: Amphora,
  apple: Apple,
  arrowDown: ArrowDown,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUp: ArrowUp,
  arrowUpRight: ArrowUpRight,
  atSign: AtSign,
  award: Award,
  badgeCheck: BadgeCheck,
  badgeInfo: BadgeInfo,
  banana: Banana,
  bookOpenCheck: BookOpenCheck,
  bottleWine: BottleWine,
  briefcaseBusiness: BriefcaseBusiness,
  calendarCheck: CalendarCheck,
  calendarDays: CalendarDays,
  check: Check,
  chefHat: ChefHat,
  cherry: Cherry,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  chevronsDownUp: ChevronsDownUp,
  chevronsUpDown: ChevronsUpDown,
  circlePlay: CirclePlay,
  circleStar: CircleStar,
  citrus: Citrus,
  clipboardCheck: ClipboardCheck,
  clock: Clock,
  conciergeBell: ConciergeBell,
  cookie: Cookie,
  copy: Copy,
  cornerRightUp: CornerRightUp,
  croissant: Croissant,
  crown: Crown,
  download: Download,
  droplets: Droplets,
  externalLink: ExternalLink,
  facebook: Facebook,
  fileBadge: FileBadge,
  fileText: FileText,
  fish: Fish,
  flame: Flame,
  flaskConical: FlaskConical,
  flower2: Flower2,
  gem: Gem,
  glassWater: GlassWater,
  globe: Globe,
  grape: Grape,
  handshake: Handshake,
  houseHeart: HouseHeart,
  instagram: Instagram,
  layers: Layers,
  leaf: Leaf,
  linkedin: Linkedin,
  list: List,
  loaderCircle: LoaderCircle,
  lock: Lock,
  lockOpen: LockOpen,
  lockKeyhole: LockKeyhole,
  lockKeyholeOpen: LockKeyholeOpen,
  logIn: LogIn,
  mail: Mail,
  mapPin: MapPin,
  martini: Martini,
  medal: Medal,
  menu: Menu,
  mountain: Mountain,
  nut: Nut,
  phoneCall: PhoneCall,
  phoneIncoming: PhoneIncoming,
  phoneOutgoing: PhoneOutgoing,
  plus: Plus,
  search: Search,
  shieldCheck: ShieldCheck,
  shieldEllipsis: ShieldEllipsis,
  snowflake: Snowflake,
  sparkles: Sparkles,
  sprout: Sprout,
  star: Star,
  sun: Sun,
  thermometerSnowflake: ThermometerSnowflake,
  trash: Trash,
  trophy: Trophy,
  user: User,
  userCog: UserCog,
  userRoundCheck: UserRoundCheck,
  userStar: UserStar,
  users: Users,
  utensilsCrossed: UtensilsCrossed,
  wheat: Wheat,
  wine: Wine,
  x: X,
  youtube: Youtube,
} as const;

export type IconName = keyof typeof iconMap;
