import {
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  AtSign,
  BadgeCheck,
  BadgeInfo,
  BookOpenCheck,
  BriefcaseBusiness,
  CalendarCheck,
  CalendarDays,
  Car,
  CarFront,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsDownUp,
  ChevronsUpDown,
  ChevronUp,
  CircleGauge,
  CirclePlay,
  CircleStar,
  ClipboardCheck,
  Clock,
  Copy,
  CornerRightUp,
  Crown,
  Dog,
  Download,
  ExternalLink,
  Facebook,
  FileBadge,
  FileText,
  Gem,
  Handshake,
  Headset,
  Hourglass,
  HouseHeart,
  Instagram,
  Layers,
  Linkedin,
  List,
  LoaderCircle,
  Lock,
  LockKeyhole,
  LockKeyholeOpen,
  LockOpen,
  LogIn,
  Mail,
  Menu,
  Moon,
  MoonStar,
  MountainSnow,
  PhoneCall,
  PhoneIncoming,
  PhoneOutgoing,
  Plane,
  Plus,
  Search,
  ShieldCheck,
  ShieldEllipsis,
  Ship,
  Sun,
  Trash,
  Triangle,
  Trophy,
  User,
  UserCog,
  UserRoundCheck,
  UserStar,
  Users,
  X,
  Youtube,
} from "lucide-react";

export const iconMap = {
  arrowDown: ArrowDown,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUp: ArrowUp,
  arrowUpRight: ArrowUpRight,
  atSign: AtSign,
  badgeCheck: BadgeCheck,
  badgeInfo: BadgeInfo,
  bookOpenCheck: BookOpenCheck,
  briefcaseBusiness: BriefcaseBusiness,
  calendarCheck: CalendarCheck,
  calendarDays: CalendarDays,
  car: Car,
  carFront: CarFront,
  check: Check,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  chevronsDownUp: ChevronsDownUp,
  chevronsUpDown: ChevronsUpDown,
  circleGauge: CircleGauge,
  circlePlay: CirclePlay,
  circleStar: CircleStar,
  clipboardCheck: ClipboardCheck,
  clock: Clock,
  copy: Copy,
  cornerRightUp: CornerRightUp,
  crown: Crown,
  dog: Dog,
  download: Download,
  externalLink: ExternalLink,
  facebook: Facebook,
  fileBadge: FileBadge,
  fileText: FileText,
  gem: Gem,
  handshake: Handshake,
  headset: Headset,
  hourglass: Hourglass,
  houseHeart: HouseHeart,
  instagram: Instagram,
  layers: Layers,
  linkedin: Linkedin,
  list: List,
  loaderCircle: LoaderCircle,
  lock: Lock,
  lockOpen: LockOpen,
  lockKeyhole: LockKeyhole,
  lockKeyholeOpen: LockKeyholeOpen,
  logIn: LogIn,
  mail: Mail,
  menu: Menu,
  moon: Moon,
  moonStar: MoonStar,
  mountainSnow: MountainSnow,
  phoneCall: PhoneCall,
  phoneIncoming: PhoneIncoming,
  phoneOutgoing: PhoneOutgoing,
  plane: Plane,
  plus: Plus,
  search: Search,
  ship: Ship,
  shieldCheck: ShieldCheck,
  shieldEllipsis: ShieldEllipsis,
  sun: Sun,
  trash: Trash,
  triangle: Triangle,
  trophy: Trophy,
  user: User,
  userCog: UserCog,
  userRoundCheck: UserRoundCheck,
  userStar: UserStar,
  users: Users,
  x: X,
  youtube: Youtube,
} as const;

export type IconName = keyof typeof iconMap;
